export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST"
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAIL = "CREATE_COURSE_FAIL"

export const LOAD_COURSES_REQUEST = "LOAD_COURSES_REQUEST"
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS"
export const LOAD_COURSES_FAIL = "LOAD_COURSES_FAIL"

export const LOAD_COURSE_REQUEST = "LOAD_COURSE_REQUEST"
export const LOAD_COURSE_SUCCESS = "LOAD_COURSE_SUCCESS"
export const LOAD_COURSE_FAIL = "LOAD_COURSE_FAIL"
